# Generated by Django 4.1.1 on 2022-11-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name_of_activity", models.CharField(max_length=250)),
                ("activity_description", models.TextField(max_length=400)),
                ("activity_category", models.CharField(max_length=250)),
                ("category_reference", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name_plural": "activities",
                "db_table": "activity",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="ActivityCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("categoryname", models.CharField(max_length=250, unique=True)),
            ],
            options={
                "verbose_name_plural": "activitycategories",
                "db_table": "activity_category",
            },
        ),
        migrations.CreateModel(
            name="Activityfrequency",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("activityname", models.CharField(max_length=250, unique=True)),
            ],
            options={
                "verbose_name_plural": "activityfrequencies",
                "db_table": "activity_frequency",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="CategoryType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("categorytype", models.CharField(max_length=250, unique=True)),
                ("description", models.CharField(max_length=250, unique=True)),
            ],
            options={
                "verbose_name_plural": "category_types",
                "db_table": "category_type",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=250, null=True, unique=True
                    ),
                ),
                (
                    "company_description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                "db_table": "company",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dept_name", models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                "db_table": "department",
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=250, unique=True)),
            ],
            options={
                "verbose_name_plural": "status",
                "db_table": "status",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "tasks",
                "db_table": "task",
            },
        ),
        migrations.CreateModel(
            name="Usertask",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("comments", models.CharField(blank=True, max_length=50, null=True)),
                ("Time_of_opened", models.DateTimeField(blank=True, null=True)),
                (
                    "support_documents",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/%d/%m/%Y/"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Usertasks",
                "db_table": "user_task",
                "ordering": ("-id",),
            },
        ),
    ]
