# Generated by Django 4.1.1 on 2022-11-28 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taskapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertask",
            name="inserted_by",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usertask",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="taskapp.status",
            ),
        ),
        migrations.AddField(
            model_name="usertask",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="taskapp.task",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="taskapp.activity"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="taskapp.status",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="taskapp.company"
            ),
        ),
        migrations.AddField(
            model_name="categorytype",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="taskapp.activitycategory",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="activity_frequency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="taskapp.activityfrequency",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="taskapp.company"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="taskapp.department"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("dept_name", "company")},
        ),
    ]
